// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_UOx-ek0vyJ3WVVzZbdMU0piKKrdX6Ck',
    appId: '1:717384169081:web:9ddc4636ddf453c1ba86a8',
    messagingSenderId: '717384169081',
    projectId: 'portfolio-1799f',
    authDomain: 'portfolio-1799f.firebaseapp.com',
    storageBucket: 'portfolio-1799f.firebasestorage.app',
    measurementId: 'G-FRF1ZR0GFF',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv9zSn04xXR8bJphhLTtwZGDmuGXTE7Jw',
    appId: '1:717384169081:ios:aa82c96a3b1c7df9ba86a8',
    messagingSenderId: '717384169081',
    projectId: 'portfolio-1799f',
    storageBucket: 'portfolio-1799f.firebasestorage.app',
    iosBundleId: 'com.example.portfolio',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGQEQMA-r2CG_QpQigLxEad1O-0f_Yb0',
    appId: '1:717384169081:android:db56ed4ef647ee24ba86a8',
    messagingSenderId: '717384169081',
    projectId: 'portfolio-1799f',
    storageBucket: 'portfolio-1799f.firebasestorage.app',
  );
}
